"use client";
import { useRef, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { api } from "@/lib/api";
import { useWorkspace, type OfficeLocation } from "@/lib/store";
import { OFFICE_ROWS, OFFICE_COLUMNS, cellKeyTarget, cellWindow, movedCellWindow, columnName, officeCellText, officeValueText, parseCellRange, rangeLabel } from "@/lib/office-reader";
import { groupedWarningTexts } from "@/lib/warnings";
import type { OfficeCell, OfficeUnit, Source } from "@/lib/types";
import { Button } from "./ui/button";
import { useErrorText } from "./ui/error-text";
import { officeTableColumnNames, record, objects, text } from "@/lib/office-structure";
export function XlsxContent({ opened, sheetId, revision, source, sheetName, unit }: { opened: OfficeLocation; sheetId: string; revision: string; source: Source | null; sheetName: string; unit?: OfficeUnit }) {
  const state = useWorkspace(); const errorText = useErrorText(); const [rangeInput, setRangeInput] = useState(""); const [failure, setFailure] = useState(""); const [inspected, setInspected] = useState<{ row: number; column: number } | null>(null);
  const buttons = useRef(new Map<string, HTMLButtonElement>());
  const requested = opened.cellRange ?? { rowStart: 1, rowEnd: OFFICE_ROWS, columnStart: 1, columnEnd: OFFICE_COLUMNS };
  const windowRange = cellWindow(requested);
  const cells = useQuery({ queryKey: ["office-cells", opened.versionId, revision, sheetId, windowRange], queryFn: ({ signal }) => api.officeCells(opened.versionId, sheetId, revision, windowRange, signal), staleTime: 30000 });
  const indexed = new Map((cells.data?.cells ?? []).map(cell => [`${cell.row}:${cell.column}`, cell]));
  const active: OfficeCell | undefined = inspected ? indexed.get(`${inspected.row}:${inspected.column}`) : undefined;
  const showRange = () => { const range = parseCellRange(rangeInput); if (!range) { setFailure("Saisissez une adresse ou une plage valide, par exemple B2:D12."); return; } setFailure(""); state.officeLocation({ cellRange: range }); };
  const move = (row: number, column: number) => { setInspected(null); state.officeLocation({ cellRange: movedCellWindow(row, column) }); };
  const focusCell = inspected && inspected.row >= windowRange.rowStart && inspected.row <= windowRange.rowEnd && inspected.column >= windowRange.columnStart && inspected.column <= windowRange.columnEnd ? inspected : { row: windowRange.rowStart, column: windowRange.columnStart };
  const metadata = { ...unit?.metadata, ...cells.data?.metadata };
  const mergedRanges = Array.isArray(metadata.merged_ranges) ? metadata.merged_ranges.filter((range): range is string => typeof range === "string") : [];
  const tables = cells.data?.tables ?? objects(metadata.tables);
  const merged = inspected ? mergedRanges.find(label => { const range = parseCellRange(label); return range && inspected.row >= range.rowStart && inspected.row <= range.rowEnd && inspected.column >= range.columnStart && inspected.column <= range.columnEnd; }) : undefined;
  const cited = source?.locator?.kind === "xlsx_cells" && source.version_id === opened.versionId && source.extraction_revision_id === revision && source.locator.sheet_id === sheetId ? source.locator : null;
  return <div className="office-spreadsheet"><div className="office-window-controls">
    <label>Adresse ou plage<input value={rangeInput} placeholder="B2:D12" onChange={event => setRangeInput(event.target.value)} onKeyDown={event => { if (event.key === "Enter") showRange(); }} /></label><Button size="sm" variant="secondary" onClick={showRange}>Afficher</Button>
    <Button size="sm" variant="secondary" onClick={() => state.setScope({ kind: "sheet", versionId: opened.versionId, extractionRevisionId: revision, sheetId }, `${sheetName} · feuille entière`)}>Analyser cette feuille</Button>
    <Button size="sm" variant="secondary" onClick={() => state.setScope({ kind: "cell_range", versionId: opened.versionId, extractionRevisionId: revision, sheetId, ...requested }, `${sheetName} · ${rangeLabel(requested)}`)}>Analyser cette plage</Button></div>
    <p className="office-help">Fenêtre {rangeLabel(windowRange)}. La lecture ne change pas le périmètre. Les formules ne sont pas recalculées ; la fraîcheur des valeurs en cache est inconnue. Dans le tableau, utilisez les flèches, Début et Fin pour parcourir les cellules.</p>
    <div className="office-window-controls"><Button size="sm" variant="ghost" disabled={windowRange.rowStart === 1} onClick={() => move(windowRange.rowStart - OFFICE_ROWS, windowRange.columnStart)}>Lignes précédentes</Button><Button size="sm" variant="ghost" disabled={windowRange.rowEnd === 1_048_576} onClick={() => move(windowRange.rowStart + OFFICE_ROWS, windowRange.columnStart)}>Lignes suivantes</Button><Button size="sm" variant="ghost" disabled={windowRange.columnStart === 1} onClick={() => move(windowRange.rowStart, windowRange.columnStart - OFFICE_COLUMNS)}>Colonnes précédentes</Button><Button size="sm" variant="ghost" disabled={windowRange.columnEnd === 16_384} onClick={() => move(windowRange.rowStart, windowRange.columnStart + OFFICE_COLUMNS)}>Colonnes suivantes</Button></div>
    {failure && <p role="alert" className="inline-error">{failure}</p>}{cells.isLoading && <p role="status">Chargement des cellules…</p>}{cells.isError && <p role="alert" className="inline-error">{errorText(cells.error)}</p>}
    {cells.data && <div className="office-table-scroll"><table><caption>{sheetName} · {rangeLabel(windowRange)}</caption><thead><tr><th scope="col">Ligne</th>{Array.from({ length: windowRange.columnEnd - windowRange.columnStart + 1 }, (_, offset) => <th scope="col" key={offset}>{columnName(windowRange.columnStart + offset)}</th>)}</tr></thead><tbody>{Array.from({ length: windowRange.rowEnd - windowRange.rowStart + 1 }, (_, rowOffset) => {
      const row = windowRange.rowStart + rowOffset;
      return <tr key={row}><th scope="row">{row}</th>{Array.from({ length: windowRange.columnEnd - windowRange.columnStart + 1 }, (_, columnOffset) => { const column = windowRange.columnStart + columnOffset; const cell = indexed.get(`${row}:${column}`); const address = `${columnName(column)}${row}`; const highlighted = cited && row >= cited.row_start && row <= cited.row_end && column >= cited.column_start && column <= cited.column_end;
        return <td key={column} className={highlighted ? "is-cited" : undefined}><button ref={button => { if (button) buttons.current.set(`${row}:${column}`, button); else buttons.current.delete(`${row}:${column}`); }} type="button" className="office-cell" data-address={address} tabIndex={focusCell.row === row && focusCell.column === column ? 0 : -1} aria-label={`${address} : ${cell ? officeCellText(cell) || (cell.formula && !cell.cached_present ? "formule sans valeur en cache" : "cellule vide") : "aucune cellule enregistrée"}${highlighted ? " · source citée" : ""}`} aria-pressed={inspected?.row === row && inspected.column === column} onClick={() => setInspected({ row, column })} onKeyDown={event => { const target = cellKeyTarget(event.key, row, column, windowRange, event.ctrlKey || event.metaKey); if (!target) return; event.preventDefault(); setInspected(target); buttons.current.get(`${target.row}:${target.column}`)?.focus(); }}>{cell ? officeCellText(cell) : ""}{cell?.formula && <small title="Formule conservée, jamais exécutée">ƒ</small>}</button></td>;
      })}</tr>;
    })}</tbody></table></div>}
    {inspected && <section className="office-cell-inspector" aria-label="Détail de la cellule"><h3>{columnName(inspected.column)}{inspected.row}</h3>{merged && <p>Cellule appartenant à la fusion {merged}. Le texte source n'est pas dupliqué dans les cellules de continuation.</p>}{active ? <dl><dt>Valeur affichée</dt><dd>{officeCellText(active) || "Aucune valeur affichée"}</dd><dt>Type</dt><dd>{active.data_type}</dd><dt>Valeur source</dt><dd>{text(active.raw_value)}</dd><dt>Format</dt><dd>{active.number_format ?? "Non renseigné"}</dd>{active.formula && <><dt>Formule source</dt><dd className="mono">{active.formula.raw_text ?? "Texte source absent pour cette formule partagée"}</dd>{active.formula.effective_text !== active.formula.raw_text && <><dt>Formule effective</dt><dd className="mono">{active.formula.effective_text ?? "Non résolue"} · dérivée de la formule source</dd></>}<dt>Type de formule</dt><dd>{active.formula.type ?? "Ordinaire"}{record(active.formula.attributes).ref ? ` · plage ${text(record(active.formula.attributes).ref)}` : ""}{active.formula.shared_source_address ? ` · source partagée ${text(active.formula.shared_source_address)}` : ""}</dd><dt>Valeur en cache</dt><dd>{active.cached_present ? officeValueText(active.cached_value) : "Cache absent"}</dd><dt>Fraîcheur</dt><dd>{active.cache_freshness === "absent" ? "Aucun cache disponible" : "Inconnue ; aucun recalcul effectué"}</dd><dt>Relations de la formule</dt><dd>{(Array.isArray(active.formula.references) ? active.formula.references : []).slice(0, 100).map((reference, index) => <p key={index}>{typeof reference === "string" ? reference : text(record(reference).reference ?? record(reference).text)}</p>)}{active.formula.external_reference_present === true && <p>Liaison externe conservée, jamais ouverte.</p>}<p>{active.formula.references_coverage === "unresolved" ? "Certaines références ne sont pas résolues." : "Opérandes reconnus ; ceci ne prouve pas une évaluation complète de la formule."}</p></dd></>}{active.cell_metadata != null && <><dt>Métadonnées de cellule</dt><dd>Enregistrement {text(record(active.cell_metadata).index)} · partie {text(record(active.cell_metadata).part)}{active.formula?.dynamic_array_metadata != null ? " · formule de tableau dynamique conservée comme métadonnée source" : ""}</dd></>}{active.comment != null && <><dt>Commentaire</dt><dd>{text(record(active.comment).author)} : {text(record(active.comment).text)}</dd></>}</dl> : <p>Aucune cellule source enregistrée à cette adresse dans la fenêtre.</p>}</section>}
    <details className="office-metadata"><summary>Structure et relations de la feuille</summary><p>{tables.length} tableau(x) structuré(s) · {mergedRanges.length} fusion(s). Les liens sources restent des données, sans navigation externe automatique.</p>{tables.slice(0, 50).map((table, index) => <div key={text(table.id) || index}><h3>{text(table.name) || "Tableau sans nom"} · {text(table.cell_range)}</h3><p>Colonnes : {officeTableColumnNames(table).join(" · ") || "Non renseignées"}</p></div>)}{mergedRanges.length > 0 && <p>Fusions : {mergedRanges.slice(0, 100).join(" · ")}{mergedRanges.length > 100 ? " · liste limitée aux 100 premières" : ""}</p>}{objects(metadata.hyperlinks).slice(0, 50).map((link, index) => <p key={`link-${index}`}>Lien {text(link.cell_range ?? link.ref)} : {text(link.location ?? link.target)} · {link.external === true ? "externe" : "interne"}</p>)}{objects(metadata.relations).slice(0, 50).map((relation, index) => <p key={`relation-${index}`}>Relation : {text(relation.type).split("/").at(-1)} · {text(relation.target)}{relation.external === true ? " · externe, non ouverte" : ""}</p>)}</details>
    {groupedWarningTexts(cells.data?.warnings).map(message => <p className="inline-warning" key={message}>{message}</p>)}
  </div>;
}
